/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#bec6e0",
        "surface-bright": "#faf8ff",
        "safety-blue": "#EFF6FF",
        "inverse-on-surface": "#f0f0fb",
        "on-secondary-fixed": "#131b2e",
        "slate-600": "#475569",
        "surface-container-low": "#f3f3fe",
        "primary-fixed-dim": "#b4c5ff",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e1e2ed",
        "error-container": "#ffdad6",
        "surface-variant": "#e1e2ed",
        "on-surface": "#191b23",
        "surface-dim": "#d9d9e5",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#b4c5ff",
        "surface-container": "#ededf9",
        "on-tertiary-container": "#ffede6",
        "primary-container": "#2563eb",
        "on-secondary-container": "#5c647a",
        "tertiary-fixed-dim": "#ffb596",
        "outline": "#737686",
        "on-background": "#191b23",
        "slate-900": "#0F172A",
        "on-tertiary-fixed": "#360f00",
        "secondary": "#565e74",
        "on-surface-variant": "#434655",
        "primary-fixed": "#dbe1ff",
        "on-error": "#ffffff",
        "secondary-fixed": "#dae2fd",
        "background": "#faf8ff",
        "danger-red": "#DC2626",
        "on-primary-fixed-variant": "#003ea8",
        "tertiary": "#943700",
        "on-tertiary-fixed-variant": "#7d2d00",
        "surface": "#faf8ff",
        "secondary-container": "#dae2fd",
        "surface-container-high": "#e7e7f3",
        "inverse-surface": "#2e3039",
        "on-primary-container": "#eeefff",
        "on-error-container": "#93000a",
        "alert-amber": "#D97706",
        "primary": "#004ac6",
        "surface-tint": "#0053db",
        "trust-blue": "#2563EB",
        "deep-navy": "#0F172A",
        "tertiary-fixed": "#ffdbcd",
        "on-primary-fixed": "#00174b",
        "on-tertiary": "#ffffff",
        "success-green": "#059669",
        "on-secondary-fixed-variant": "#3f465c",
        "on-primary": "#ffffff",
        "outline-variant": "#c3c6d7",
        "tertiary-container": "#bc4800",
        "slate-50": "#F8FAFC"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "base": "8px",
        "container-max": "1200px",
        "stack-sm": "8px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-xl": ["Public Sans"],
        "label-sm": ["Public Sans"],
        "body-lg": ["Public Sans"],
        "label-caps": ["Public Sans"],
        "body-md": ["Public Sans"],
        "body-sm": ["Public Sans"],
        "headline-md": ["Public Sans"],
        "headline-lg": ["Public Sans"],
        "headline-lg-mobile": ["Public Sans"]
      },
      fontSize: {
        "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
